# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main
  - development

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar'
      organization: 'bootcamp-devops-sonar'
      scannerMode: 'Other'
      extraProperties:
        sonar.projectKey=edwinmarr_bootcamp-devops
        sonar.projectName=bootcamp-devops
  - task: Gradle@3
    displayName: 'Ejecutar tareas gradle'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build'
      jdkVersionOption: 1.17
      sonarQubeRunAnalysis: true
      sonarQubeGradlePluginVersion: 4.3.0.3225
      codeCoverageGradle5xOrHigher: true
  - task: SonarCloudAnalyze@1
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'users-to-hexagonal-artifact'
      publishLocation: 'Container'
      MaxArtifactSize: 0