# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - development

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'users-to-hexagonal/gradlew'
      workingDirectory: 'users-to-hexagonal'
      tasks: 'clean build'
      jdkVersionOption: 1.17
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'users-to-hexagonal-artifact'
      publishLocation: 'Container'
      MaxArtifactSize: 0

