# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main
  - development

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
  - task: SonarCloudPrepare@1
    displayName: "Preparing sonar cloud"
    inputs:
      SonarCloud: 'Sonar'
      organization: 'bootcamp-devops-sonar'
      scannerMode: 'Other'
  - task: Gradle@3
    displayName: 'Building gradle project'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build sonar'
      jdkVersionOption: 1.17
      
  - task: SonarCloudPublish@1
    displayName: 'Publishing sonarResults'
    inputs:
      pollingTimeoutSec: '300'

  - task: SonarCloudQualityGateCheck@1
    displayName: 'SonarCloud Quality Gate'

  - task: PublishBuildArtifacts@1
    displayName: 'Publishing artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'users-to-hexagonal-artifact'
      publishLocation: 'Container'
      MaxArtifactSize: 0