spring:
  application:
    name: users-to-hexagonal
  host: ${HOST:localhost}
  port: ${PORT:8080}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://endpoint_bd}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true
