spring:
  application:
    name: users-to-hexagonal
  host: ${HOST:localhost}
  port: ${PORT:8080}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://database-bootcamp-devops.cunmkxbsc3md.us-east-1.rds.amazonaws.com:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:bootcamp2023-devops}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true

external-api:
  url: ${HELLO_WORLD_URL:localhost:8085}